# Generated by Django 4.2 on 2026-05-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit', models.CharField(default='份', max_length=10, verbose_name='单位')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='商品图片')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('icon', models.CharField(default='📦', max_length=50, verbose_name='分类图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='GoodsSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='规格名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='规格价格')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.goods', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'db_table': 'goods_spec',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='所属分类'),
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('flash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='秒杀价格')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('stock', models.IntegerField(default=0, verbose_name='秒杀库存')),
                ('sold', models.IntegerField(default=0, verbose_name='已售数量')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='秒杀商品')),
            ],
            options={
                'verbose_name': '秒杀活动',
                'verbose_name_plural': '秒杀活动',
                'db_table': 'flash_sale',
            },
        ),
    ]
