# Generated by Django 4.2 on 2026-05-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='icon',
            field=models.CharField(default='daily', max_length=50, verbose_name='分类图标'),
        ),
    ]
