# Generated by Django 4.2 on 2026-05-23 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_alter_goodscategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.IntegerField(default=5, verbose_name='评分')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goods.goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'goods_comment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('image', models.ImageField(upload_to='comments/', verbose_name='图片')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goodscomment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论图片',
                'verbose_name_plural': '评论图片',
                'db_table': 'comment_image',
            },
        ),
    ]
