# Generated by Django 4.2 on 2026-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodscomment_commentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashsale/', verbose_name='秒杀图片'),
        ),
    ]
