# Generated by Django 4.2 on 2026-05-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_flashsale_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='套餐描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='combo/', verbose_name='套餐图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='套餐价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'db_table': 'combo',
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.combo', verbose_name='所属套餐')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '套餐商品',
                'verbose_name_plural': '套餐商品',
                'db_table': 'combo_item',
            },
        ),
    ]
