# Generated by Django 4.2 on 2026-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='手机号'),
        ),
    ]
