# Generated by Django 4.2 on 2026-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
    ]
